import { HealthTip } from '../types';

export const healthTips: HealthTip[] = [
  // DIET
  { id: 'd1', title: 'Eat More Fiber', description: 'Fiber keeps you full longer and aids digestion.', fullText: 'Dietary fiber is essential for maintaining a healthy digestive system. It helps regulate blood sugar levels, lowers cholesterol, and keeps you feeling full longer, which can help with weight management. Aim for 25-30 grams of fiber per day from sources like whole grains, fruits, vegetables, and legumes.', category: 'diet', emoji: '🥦', bmiCategories: ['Overweight', 'Obese Class I', 'Obese Class II', 'Obese Class III'] },
  { id: 'd2', title: 'Hydration Matters', description: 'Drink at least 8 glasses of water daily.', fullText: 'Staying properly hydrated is crucial for every bodily function. Water helps regulate body temperature, transport nutrients, flush toxins, and can even boost metabolism. Aim for at least 8 glasses (2 liters) of water per day, more if you exercise or live in a hot climate. Sometimes thirst is mistaken for hunger, so drinking water before meals can help with portion control.', category: 'diet', emoji: '💧', bmiCategories: ['Normal', 'Overweight', 'Obese Class I', 'Obese Class II', 'Obese Class III'] },
  { id: 'd3', title: 'Balanced Macros', description: 'Ensure a good balance of protein, carbs, and fats.', fullText: 'A balanced diet includes the right proportion of macronutrients: carbohydrates for energy (45-65% of calories), protein for muscle repair and growth (10-35%), and healthy fats for brain function and hormone production (20-35%). Focus on complex carbs, lean proteins, and unsaturated fats for optimal health.', category: 'diet', emoji: '🍽️', bmiCategories: ['Normal', 'Overweight', 'Mild Thinness'] },
  { id: 'd4', title: 'Mindful Eating', description: 'Pay attention to what and how you eat.', fullText: 'Mindful eating means being fully present during meals. Eat slowly, chew thoroughly, and savor each bite. This practice helps you recognize hunger and fullness cues, prevents overeating, and can improve digestion. Put away screens during meals and focus on the taste, texture, and aroma of your food.', category: 'diet', emoji: '🧘', bmiCategories: ['Overweight', 'Obese Class I', 'Obese Class II', 'Obese Class III'] },
  { id: 'd5', title: 'Portion Control', description: 'Use smaller plates to manage portion sizes.', fullText: 'Research shows that using smaller plates and bowls can naturally reduce how much you eat by 20-30%. The visual illusion of a full smaller plate tricks your brain into feeling satisfied with less food. Also, try pre-portioning snacks instead of eating from the bag, and fill half your plate with vegetables.', category: 'diet', emoji: '🍽️', bmiCategories: ['Overweight', 'Obese Class I', 'Obese Class II', 'Obese Class III'] },
  { id: 'd6', title: 'Reduce Sugar Intake', description: 'Cut down on added sugars for better health.', fullText: 'Excessive sugar consumption is linked to obesity, type 2 diabetes, heart disease, and tooth decay. The WHO recommends limiting added sugars to less than 10% of daily calories (about 50g). Watch out for hidden sugars in processed foods, sauces, and drinks. Choose whole fruits over fruit juices and opt for water instead of sugary beverages.', category: 'diet', emoji: '🚫', bmiCategories: ['Overweight', 'Obese Class I', 'Obese Class II', 'Obese Class III'] },
  { id: 'd7', title: 'Eat More Vegetables', description: 'Aim for 5 servings of fruits and veggies daily.', fullText: 'Vegetables are packed with essential vitamins, minerals, fiber, and antioxidants while being low in calories. Eating a variety of colorful vegetables ensures you get a wide range of nutrients. Try to fill half your plate with vegetables at each meal. Dark leafy greens, cruciferous vegetables, and brightly colored produce are especially beneficial.', category: 'diet', emoji: '🥗', bmiCategories: ['Normal', 'Overweight', 'Obese Class I', 'Mild Thinness'] },
  { id: 'd8', title: 'Healthy Snacking', description: 'Choose nuts, fruits, or yogurt over chips.', fullText: 'Smart snacking can help maintain energy levels and prevent overeating at meals. Choose nutrient-dense snacks like nuts and seeds, fresh fruits, Greek yogurt, hummus with vegetables, or whole-grain crackers. Prepare healthy snacks in advance so they are readily available when hunger strikes. Avoid keeping junk food easily accessible.', category: 'diet', emoji: '🥜', bmiCategories: ['Normal', 'Overweight', 'Mild Thinness'] },

  // EXERCISE
  { id: 'e1', title: '30 Minutes Daily', description: 'Just 30 minutes of moderate exercise makes a difference.', fullText: 'The WHO recommends at least 150 minutes of moderate-intensity aerobic activity per week, which breaks down to about 30 minutes, 5 days a week. This can include brisk walking, cycling, swimming, or dancing. Regular exercise reduces the risk of heart disease, diabetes, depression, and many cancers. Start with what you can do and gradually increase duration and intensity.', category: 'exercise', emoji: '🏃', bmiCategories: ['Normal', 'Overweight', 'Obese Class I', 'Obese Class II'] },
  { id: 'e2', title: 'Strength Training', description: 'Build muscle to boost metabolism.', fullText: 'Strength training, or resistance exercise, helps build and maintain muscle mass, which naturally declines with age. More muscle means a higher resting metabolic rate, helping you burn more calories even at rest. Aim for at least 2 sessions per week targeting all major muscle groups. You can use weights, resistance bands, or your own body weight.', category: 'exercise', emoji: '💪', bmiCategories: ['Normal', 'Overweight', 'Obese Class I', 'Mild Thinness'] },
  { id: 'e3', title: 'Take the Stairs', description: 'Small changes add up to big health gains.', fullText: 'Choosing stairs over elevators is one of the easiest ways to add physical activity to your daily routine. Climbing stairs burns 2-3 times more calories than walking on flat ground and strengthens your leg muscles, improves cardiovascular health, and boosts your endurance. Even just a few flights per day can make a meaningful difference over time.', category: 'exercise', emoji: '🪜', bmiCategories: ['Normal', 'Overweight', 'Obese Class I'] },
  { id: 'e4', title: 'Morning Stretches', description: 'Start your day with gentle stretching.', fullText: 'Morning stretching helps wake up your muscles, increases blood flow, improves flexibility, and sets a positive tone for the day. Spend 5-10 minutes doing gentle stretches targeting your neck, shoulders, back, hips, and legs. This can reduce stiffness, improve posture, and decrease the risk of injury during daily activities.', category: 'exercise', emoji: '🤸', bmiCategories: ['Normal', 'Overweight', 'Mild Thinness', 'Severe Thinness'] },
  { id: 'e5', title: 'Walk After Meals', description: 'A 15-minute walk after eating aids digestion.', fullText: 'Walking after meals, especially after dinner, can significantly improve digestion and help regulate blood sugar levels. Studies show that a 15-minute post-meal walk can lower blood sugar spikes by up to 30%. It also helps with calorie burning and can improve sleep quality when done after the evening meal.', category: 'exercise', emoji: '🚶', bmiCategories: ['Normal', 'Overweight', 'Obese Class I', 'Obese Class II'] },
  { id: 'e6', title: 'Find a Workout Buddy', description: 'Exercising with others boosts motivation.', fullText: 'Research shows that people who exercise with a partner are more consistent and work out longer. A workout buddy provides accountability, motivation, and makes exercise more enjoyable. You can challenge each other, try new activities together, and celebrate achievements. Even virtual workout partners through apps can provide similar benefits.', category: 'exercise', emoji: '👥', bmiCategories: ['Normal', 'Overweight', 'Obese Class I'] },

  // LIFESTYLE
  { id: 'l1', title: 'Sleep 7-9 Hours', description: 'Quality sleep is crucial for weight management.', fullText: 'Sleep deprivation disrupts hormones that regulate appetite (ghrelin and leptin), leading to increased hunger and cravings for high-calorie foods. Adults need 7-9 hours of quality sleep per night. Poor sleep is linked to weight gain, decreased metabolism, and increased risk of obesity. Establish a consistent sleep schedule and create a relaxing bedtime routine.', category: 'lifestyle', emoji: '😴', bmiCategories: ['Normal', 'Overweight', 'Obese Class I', 'Obese Class II'] },
  { id: 'l2', title: 'Reduce Screen Time', description: 'Limit recreational screen time to 2 hours.', fullText: 'Excessive screen time is associated with sedentary behavior, poor sleep quality, and mindless snacking. Try to limit recreational screen time to 2 hours per day. Take regular breaks if you work at a computer (the 20-20-20 rule: every 20 minutes, look at something 20 feet away for 20 seconds). Replace some screen time with physical activities or social interactions.', category: 'lifestyle', emoji: '📱', bmiCategories: ['Normal', 'Overweight', 'Obese Class I'] },
  { id: 'l3', title: 'Regular Check-ups', description: 'Visit your doctor for annual health screenings.', fullText: 'Regular health check-ups can detect potential health issues early when they are most treatable. Annual screenings should include blood pressure, cholesterol levels, blood sugar, and BMI assessment. Discuss any concerns about your weight or health with your healthcare provider. Early intervention and prevention are always better than treatment.', category: 'lifestyle', emoji: '🏥', bmiCategories: ['Normal', 'Overweight', 'Obese Class I', 'Obese Class II', 'Obese Class III'] },
  { id: 'l4', title: 'Track Your Progress', description: 'Keep a journal of your health journey.', fullText: 'Tracking your food intake, exercise, weight, and measurements provides valuable data about your health journey. It helps identify patterns, keeps you accountable, and shows progress that might not be visible on the scale. Use apps, journals, or photos to document your journey. Remember, progress is not always linear, and consistency matters more than perfection.', category: 'lifestyle', emoji: '📝', bmiCategories: ['Normal', 'Overweight', 'Obese Class I', 'Mild Thinness'] },
  { id: 'l5', title: 'Set Realistic Goals', description: 'Aim for sustainable changes, not quick fixes.', fullText: 'Setting realistic, achievable goals is key to long-term success. Instead of aiming to lose 20 pounds in a month, target 1-2 pounds per week. Break larger goals into smaller milestones and celebrate each achievement. Focus on behavior changes (eating more vegetables, walking daily) rather than just numbers on the scale. Sustainable changes lead to lasting results.', category: 'lifestyle', emoji: '🎯', bmiCategories: ['Overweight', 'Obese Class I', 'Obese Class II', 'Obese Class III'] },
  { id: 'l6', title: 'Meal Prep Sundays', description: 'Prepare healthy meals for the week ahead.', fullText: 'Meal prepping saves time, money, and helps you make healthier food choices throughout the week. Dedicate a few hours on Sunday to plan and prepare meals. Cook proteins in bulk, wash and chop vegetables, and portion out snacks. Having healthy meals ready to go reduces the temptation to order takeout or grab processed convenience foods.', category: 'lifestyle', emoji: '🍱', bmiCategories: ['Normal', 'Overweight', 'Obese Class I'] },

  // MENTAL HEALTH
  { id: 'm1', title: 'Practice Gratitude', description: 'Focus on what your body can do, not just how it looks.', fullText: 'Gratitude practice can improve mental health and your relationship with your body. Instead of focusing on appearance, appreciate what your body does for you — walking, breathing, healing. Write down three things you are grateful for each day. Research shows that gratitude practice reduces stress, improves sleep, and can even boost immune function.', category: 'mental_health', emoji: '🙏', bmiCategories: ['Normal', 'Overweight', 'Obese Class I', 'Mild Thinness'] },
  { id: 'm2', title: 'Manage Stress', description: 'Chronic stress leads to weight gain and poor health.', fullText: 'Chronic stress triggers the release of cortisol, a hormone that increases appetite and promotes fat storage, especially around the abdomen. Find healthy stress management techniques: deep breathing, meditation, yoga, spending time in nature, talking to friends, or engaging in hobbies. Even 10 minutes of relaxation per day can significantly reduce stress levels.', category: 'mental_health', emoji: '🧠', bmiCategories: ['Normal', 'Overweight', 'Obese Class I', 'Obese Class II'] },
  { id: 'm3', title: 'Body Positivity', description: 'Love your body at every stage of your journey.', fullText: 'Health comes in many shapes and sizes. While BMI is a useful screening tool, it does not define your worth or complete health picture. Practice self-compassion and avoid negative self-talk. Focus on how you feel — your energy, strength, and vitality — rather than just a number. Every step toward healthier habits is worth celebrating, regardless of where you are starting from.', category: 'mental_health', emoji: '💕', bmiCategories: ['Normal', 'Overweight', 'Obese Class I', 'Mild Thinness', 'Moderate Thinness'] },
  { id: 'm4', title: 'Celebrate Small Wins', description: 'Every healthy choice matters, no matter how small.', fullText: 'Acknowledging small achievements keeps you motivated on your health journey. Chose a salad over fries? Walked an extra block? Drank enough water today? These all count! Small wins build momentum and create positive habits over time. Keep a success journal or share achievements with a supportive friend. Remember, big changes are made up of many small steps.', category: 'mental_health', emoji: '🎉', bmiCategories: ['Normal', 'Overweight', 'Obese Class I', 'Obese Class II'] },
  { id: 'm5', title: 'Seek Support', description: 'Do not hesitate to ask for help on your journey.', fullText: 'You do not have to navigate your health journey alone. Seek support from healthcare professionals, registered dietitians, personal trainers, or mental health counselors. Join support groups or online communities of people with similar goals. Having a support system significantly increases your chances of success and helps you through challenging times.', category: 'mental_health', emoji: '🤝', bmiCategories: ['Overweight', 'Obese Class I', 'Obese Class II', 'Obese Class III', 'Severe Thinness'] },

  // SLEEP
  { id: 's1', title: 'Consistent Schedule', description: 'Go to bed and wake up at the same time daily.', fullText: 'Your body has a natural circadian rhythm that thrives on consistency. Going to bed and waking up at the same time every day — even on weekends — helps regulate your internal clock, improves sleep quality, and makes it easier to fall asleep. Irregular sleep patterns are linked to weight gain, mood disorders, and decreased cognitive performance.', category: 'sleep', emoji: '⏰', bmiCategories: ['Normal', 'Overweight', 'Obese Class I'] },
  { id: 's2', title: 'Dark Room', description: 'Keep your bedroom dark for better sleep quality.', fullText: 'Light exposure at night suppresses melatonin production, the hormone that promotes sleep. Make your bedroom as dark as possible using blackout curtains or a sleep mask. Remove or cover electronic devices with standby lights. Even small amounts of light can disrupt your sleep cycle and reduce sleep quality, affecting your metabolism and appetite hormones.', category: 'sleep', emoji: '🌙', bmiCategories: ['Normal', 'Overweight', 'Obese Class I'] },
  { id: 's3', title: 'No Caffeine Late', description: 'Avoid caffeine at least 6 hours before bedtime.', fullText: 'Caffeine has a half-life of about 5-6 hours, meaning half the caffeine from your afternoon coffee is still in your system at bedtime. This can make it harder to fall asleep, reduce total sleep time, and decrease sleep quality. Set a caffeine cutoff time (usually around 2 PM) and switch to herbal tea or decaf in the afternoon and evening.', category: 'sleep', emoji: '☕', bmiCategories: ['Normal', 'Overweight', 'Obese Class I'] },
  { id: 's4', title: 'Wind Down Routine', description: 'Create a relaxing pre-sleep routine.', fullText: 'A consistent wind-down routine signals to your body that it is time to sleep. Start 30-60 minutes before bed with calming activities: reading a physical book, gentle stretching, taking a warm bath, practicing deep breathing, or listening to calm music. Avoid screens, intense exercise, heavy meals, and stimulating conversations close to bedtime.', category: 'sleep', emoji: '🛁', bmiCategories: ['Normal', 'Overweight', 'Obese Class I', 'Obese Class II'] },
  { id: 's5', title: 'Limit Naps', description: 'Keep daytime naps short — 20 minutes max.', fullText: 'While short power naps (15-20 minutes) can boost alertness and performance, longer naps can interfere with nighttime sleep. If you must nap, do so before 3 PM and keep it under 20 minutes. Long or late-afternoon naps can make it harder to fall asleep at night, creating a cycle of poor nighttime sleep and daytime drowsiness.', category: 'sleep', emoji: '💤', bmiCategories: ['Normal', 'Overweight', 'Obese Class I'] },
  { id: 's6', title: 'Cool Bedroom', description: 'Keep your bedroom temperature between 60-67°F.', fullText: 'Your body temperature naturally drops during sleep, and a cool room supports this process. The ideal sleeping temperature is between 60-67°F (15-19°C). A room that is too warm can lead to restlessness and decreased sleep quality. Use breathable bedding and consider a fan or adjusting your thermostat for optimal sleep conditions.', category: 'sleep', emoji: '❄️', bmiCategories: ['Normal', 'Overweight', 'Obese Class I'] },
];
